/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.login.view;
import br.login.dao.JardimDAO;
import br.login.dao.Sessao;
import br.login.dao.LoginDAO;
import br.login.dao.PlantaDAO;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
         // Pega o nome do usuário logado
        String email = Sessao.emailUsuarioLogado;
        LoginDAO dao = new LoginDAO();
        String nome = dao.buscarNomePorEmail(email);


        if (nome != null) {
            lblOla.setText("Olá, " + nome + "!");
            lblUser.setText(nome);
            lblEmail.setText(email);
        } else {
            lblOla.setText("Olá, usuário!");
            lblUser.setText("Usuário");
            lblEmail.setText("Email");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoPlanta = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        abasHome = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblOla = new javax.swing.JLabel();
        btnContinuarJornada = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rdbAlimenticia = new javax.swing.JRadioButton();
        rdbOrnamental = new javax.swing.JRadioButton();
        cbSolo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomePlanta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbL1 = new javax.swing.JCheckBox();
        cbL2 = new javax.swing.JCheckBox();
        cbL3 = new javax.swing.JCheckBox();
        cbL4 = new javax.swing.JCheckBox();
        cbL5 = new javax.swing.JCheckBox();
        cbL6 = new javax.swing.JCheckBox();
        bnnL1 = new javax.swing.JButton();
        bnnL2 = new javax.swing.JButton();
        bnnL3 = new javax.swing.JButton();
        bnnL4 = new javax.swing.JButton();
        bnnL5 = new javax.swing.JButton();
        bnnL6 = new javax.swing.JButton();
        panelPlantas = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Email:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOla.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblOla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnContinuarJornada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnContinuarJornada.setText("Continuar Jornada");
        btnContinuarJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarJornadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(btnContinuarJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(lblOla, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1396, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblOla, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnContinuarJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        abasHome.addTab("Navegar", jPanel1);

        grupoTipoPlanta.add(rdbAlimenticia);
        rdbAlimenticia.setText("Alimentícias");
        rdbAlimenticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAlimenticiaActionPerformed(evt);
            }
        });

        grupoTipoPlanta.add(rdbOrnamental);
        rdbOrnamental.setText("Ornamental");

        cbSolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arenoso", "Argiloso", "Siltoso", "Humífero" }));
        cbSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSoloActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Pesquise pela planta que procura");

        jLabel4.setText("Tipo de planta");

        jLabel5.setText("Solo");

        txtNomePlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePlantaActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome");

        btnPesquisar.setText("Buscar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rdbAlimenticia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbOrnamental)
                        .addGap(27, 27, 27)
                        .addComponent(cbSolo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(130, 130, 130)
                            .addComponent(jLabel5))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNomePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar))
                    .addComponent(jLabel6))
                .addContainerGap(1385, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbAlimenticia)
                    .addComponent(rdbOrnamental)
                    .addComponent(cbSolo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        abasHome.addTab("Plantas", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2211, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        abasHome.addTab("Receitas", jPanel4);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Meu Jardim");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Minha Jornada");

        cbL1.setText("Lição 1: A escolha da planta ideal");
        cbL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbL1ActionPerformed(evt);
            }
        });

        cbL2.setText("Lição 2: Preparando o material");

        cbL3.setText("Lição 3: A base de tudo: drenagem");
        cbL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbL3ActionPerformed(evt);
            }
        });

        cbL4.setText("Lição 4: Preparando o berço da planta");

        cbL5.setText("Lição 5: O grande momento do plantio");

        cbL6.setText("Lição 6: O primeiro gole de vida");

        bnnL1.setText("Ver mais");
        bnnL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL1ActionPerformed(evt);
            }
        });

        bnnL2.setText("Ver mais");
        bnnL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL2ActionPerformed(evt);
            }
        });

        bnnL3.setText("Ver mais");
        bnnL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL3ActionPerformed(evt);
            }
        });

        bnnL4.setText("Ver mais");
        bnnL4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL4ActionPerformed(evt);
            }
        });

        bnnL5.setText("Ver mais");
        bnnL5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL5ActionPerformed(evt);
            }
        });

        bnnL6.setText("Ver mais");
        bnnL6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPlantasLayout = new javax.swing.GroupLayout(panelPlantas);
        panelPlantas.setLayout(panelPlantasLayout);
        panelPlantasLayout.setHorizontalGroup(
            panelPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );
        panelPlantasLayout.setVerticalGroup(
            panelPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(panelPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(628, 628, 628)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbL1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnnL1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbL2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbL3)
                            .addComponent(cbL4)
                            .addComponent(cbL5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbL6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnnL3)
                            .addComponent(bnnL2)
                            .addComponent(bnnL4)
                            .addComponent(bnnL5)
                            .addComponent(bnnL6))))
                .addGap(197, 639, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(791, 791, 791))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbL1)
                            .addComponent(bnnL1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbL2)
                            .addComponent(bnnL2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbL3)
                            .addComponent(bnnL3))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnnL4)
                            .addComponent(cbL4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnnL5)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbL5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbL6)
                                    .addComponent(bnnL6)))))
                    .addComponent(panelPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        abasHome.addTab("Meu Jardim", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2211, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        abasHome.addTab("Comunidade", jPanel6);

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nome de Usuário:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Email:");

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1452, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        abasHome.addTab("Conta", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abasHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abasHome)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*public void atualizarMeuJardim() {
        panelPlantas.removeAll(); // limpa tudo antes

        JardimDAO dao = new JardimDAO();
        ArrayList<String> plantas = dao.buscarPlantasUsuario(Sessao.emailUsuarioLogado); // só nomes

        for (String nomePlanta : plantas) {
            JButton btnPlanta = new JButton(nomePlanta);
            btnPlanta.setCursor(new Cursor(Cursor.HAND_CURSOR));

            // ação quando clicar na planta
            btnPlanta.addActionListener(e -> {
                JOptionPane.showMessageDialog(this, "Você clicou em: " + nomePlanta);
            });

            panelPlantas.add(btnPlanta);
        }

        panelPlantas.revalidate();
        panelPlantas.repaint();
    }*/
    
    private void btnContinuarJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarJornadaActionPerformed
        // TODO add your handling code here:
        abasHome.setSelectedIndex(3);
    }//GEN-LAST:event_btnContinuarJornadaActionPerformed

    private void rdbAlimenticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAlimenticiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbAlimenticiaActionPerformed

    private void cbL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbL1ActionPerformed

    private void cbL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbL3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbL3ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // PEGAR TIPO
        String tipoPlanta = "";
        if (rdbOrnamental.isSelected()) {
            tipoPlanta = "Ornamental";
        } else if (rdbAlimenticia.isSelected()) {
            tipoPlanta = "Alimentícia";
        }

        // PEGAR SOLO
        String tipoSolo = cbSolo.getSelectedItem().toString();

        // PEGAR NOME (TEXTO)
        String nomePlanta = txtNomePlanta.getText();

        // VERIFICA TIPO
        if (tipoPlanta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione o tipo de planta!");
            return;
        }

        // CONSULTA
        br.login.dao.PlantaDAO dao = new br.login.dao.PlantaDAO();
        java.util.ArrayList<br.login.model.Planta> lista = dao.pesquisarPlantas(tipoPlanta, tipoSolo, nomePlanta);

        // SE NADA ENCONTRADO
        if (lista.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhuma planta encontrada!");
            return;
        }

        // PERMITE SELECIONAR QUAL PLANTA QUER VER
        String[] nomesPlantas = lista.stream()
                .map(p -> p.getNome())
                .toArray(String[]::new);

        String plantaSelecionada = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "Selecione a planta desejada:",
                "Resultados da Pesquisa",
                javax.swing.JOptionPane.PLAIN_MESSAGE,
                null,
                nomesPlantas,
                nomesPlantas[0]
        );

        if (plantaSelecionada == null) return; // cancelou

        // ENCONTRA OBJETO DA PLANTA ESCOLHIDA
        br.login.model.Planta p = lista.stream()
                .filter(item -> item.getNome().equals(plantaSelecionada))
                .findFirst()
                .orElse(null);

        if (p == null) return;

        // MENSAGEM BONITA
        String mensagemBonita = 
            "🌿 *Planta Encontrada!*\n\n" +
            "Nome: " + p.getNome() + "\n" +
            "Tipo: " + p.getTipo() + "\n" +
            "Solo Ideal: " + p.getSolo() + "\n\n" +
            "Descrição:\n" + p.getDescricao() + "\n\n" +
            "Deseja adicionar esta planta ao seu jardim?";

        int opcao = javax.swing.JOptionPane.showOptionDialog(
                this,
                mensagemBonita,
                "Detalhes da Planta",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.INFORMATION_MESSAGE,
                null,
                new Object[]{"Adicionar 🌱", "Fechar"},
                "Adicionar 🌱"
        );

        // SE CLICAR EM ADICIONAR 🌱
        if (opcao == 0) {

            String nomePersonalizado = javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Dê um nome à sua planta 🌿:"
            );

            if (nomePersonalizado != null && !nomePersonalizado.isEmpty()) {
                br.login.dao.JardimDAO jardimDao = new br.login.dao.JardimDAO();
                boolean sucesso = jardimDao.adicionarPlanta(
                        br.login.dao.Sessao.emailUsuarioLogado,
                        p.getNome(),
                        nomePersonalizado
                );

                if (sucesso) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Planta adicionada ao seu jardim! 🌼");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Erro ao adicionar planta.");
                }
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void bnnL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Nesta lição inicial, você aprende a base do sucesso: a compatibilidade. Você vai explorar como analisar seu ambiente,\nidentificando os níveis de luz (sol pleno, meia-sombra ou sombra), a ventilação e o espaço disponível. O objetivo é\nescolher uma planta que não apenas sobreviva, mas prospere no seu lar, alinhando as necessidades dela com a sua\nrotina e seu tempo para cuidados.",
            "Lição 1: A Escolha da Planta Ideal",
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );
    }//GEN-LAST:event_bnnL1ActionPerformed

    private void bnnL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Com sua nova companheira verde escolhida, é hora de preparar o \"enxoval\". Esta lição foca em reunir as ferramentas\ne os componentes certos. Você aprenderá sobre os diferentes tipos de vasos (barro, plástico, cerâmica) e como escolher\no tamanho ideal. Além disso, abordará a importância de selecionar o substrato (a terra) correto, garantindo a\nmistura de nutrientes que sua planta específica precisa.",
            "Lição 2: Preparando o Material",
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );
    }//GEN-LAST:event_bnnL2ActionPerformed

    private void bnnL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Esta é uma das etapas mais cruciais para a saúde a longo prazo da sua planta. O segredo para evitar o apodrecimento\ndas raízes é garantir que a água nunca se acumule no fundo do vaso. Aqui, você aprenderá a criar a camada de drenagem\nperfeita usando materiais como argila expandida ou brita, e a utilizar a manta de drenagem para impedir que o\nsubstrato obstrua os furos de escoamento.",
            "Lição 3: A Base de Tudo: Drenagem",
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );
    }//GEN-LAST:event_bnnL3ActionPerformed

    private void bnnL4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL4ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Com a drenagem pronta, é o momento de preparar a \"cama\" onde sua planta viverá. Esta lição (a que você está agora)\nensina como adicionar a primeira camada de substrato sobre a manta de drenagem. O foco é criar uma base fofa e nutritiva\nna altura certa, deixando o espaço perfeito para acomodar o torrão (a massa de terra e raízes) da planta\nsem que ela fique funda ou alta demais no vaso.",
            "Lição 4: Preparando o Berço da Planta",
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );
    }//GEN-LAST:event_bnnL4ActionPerformed

    private void bnnL5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL5ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Este é o clímax da sua jornada, o momento de unir a planta ao seu novo lar. Você aprenderá a técnica correta para\nremover a planta do vaso antigo (muitas vezes um pote plástico) com delicadeza, sem estressar ou danificar as raízes.\nEm seguida, verá como centralizar o torrão no \"berço\" que você preparou e preencher as laterais com o restante\ndo substrato, firmando a planta em sua nova casa.",
            "Lição 5: O Grande Momento do Plantio",
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );
    }//GEN-LAST:event_bnnL5ActionPerformed

    private void bnnL6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL6ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Nenhuma mudança está completa sem uma boa hidratação. A primeira rega, logo após o plantio, é fundamental.\nEsta lição explica por que você deve regar abundantemente (até a água sair pelos furos de drenagem) para assentar o substrato,\neliminar bolsas de ar e hidratar a planta após o estresse da mudança. É o toque final que dá as boas-vindas à\nplanta e inicia sua nova vida.",
            "Lição 6: O Primeiro Gole de Vida",
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );
    }//GEN-LAST:event_bnnL6ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        new LoginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void cbSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSoloActionPerformed

    private void txtNomePlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePlantaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasHome;
    private javax.swing.JButton bnnL1;
    private javax.swing.JButton bnnL2;
    private javax.swing.JButton bnnL3;
    private javax.swing.JButton bnnL4;
    private javax.swing.JButton bnnL5;
    private javax.swing.JButton bnnL6;
    private javax.swing.JButton btnContinuarJornada;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JCheckBox cbL1;
    private javax.swing.JCheckBox cbL2;
    private javax.swing.JCheckBox cbL3;
    private javax.swing.JCheckBox cbL4;
    private javax.swing.JCheckBox cbL5;
    private javax.swing.JCheckBox cbL6;
    private javax.swing.JComboBox<String> cbSolo;
    private javax.swing.ButtonGroup grupoTipoPlanta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblOla;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panelPlantas;
    private javax.swing.JRadioButton rdbAlimenticia;
    private javax.swing.JRadioButton rdbOrnamental;
    private javax.swing.JTextField txtNomePlanta;
    // End of variables declaration//GEN-END:variables
}
