/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.login.view;

import br.login.dao.JardimDAO;
import br.login.dao.Sessao;
import br.login.model.PlantaJardim;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author mayar
 */
public class MeuJardimView extends javax.swing.JFrame {

    /**
     * Creates new form MeuJardimView
     */
    public MeuJardimView() {
        initComponents();
        
        carregarPlantas();
        painelJardim.setLayout(new GridLayout(0, 2, 10, 10));//baguo de add planta, nao mexe é do panel q ta quadradinho
        
        //botoes
        this.setLocationRelativeTo(null);
        JButton[] btns={btnHome,btnPlantas,btnJardim,btnConta,bnnL1,bnnL2,bnnL3,bnnL4,bnnL5,bnnL6};
        for(JButton btn:btns){
            btn.setUI(new BasicButtonUI());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuBar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnConta = new javax.swing.JButton();
        btnPlantas = new javax.swing.JButton();
        btnJardim = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        painelJardim = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cbL1 = new javax.swing.JCheckBox();
        cbL2 = new javax.swing.JCheckBox();
        cbL3 = new javax.swing.JCheckBox();
        cbL4 = new javax.swing.JCheckBox();
        cbL5 = new javax.swing.JCheckBox();
        cbL6 = new javax.swing.JCheckBox();
        bnnL6 = new javax.swing.JButton();
        bnnL5 = new javax.swing.JButton();
        bnnL4 = new javax.swing.JButton();
        bnnL3 = new javax.swing.JButton();
        bnnL2 = new javax.swing.JButton();
        bnnL1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        MenuBar.setBackground(new java.awt.Color(0, 0, 0));
        MenuBar.setPreferredSize(new java.awt.Dimension(0, 60));
        MenuBar.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        MenuBar.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        MenuBar.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome.setText(" Home");
        btnHome.setBorder(null);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnConta.setBackground(new java.awt.Color(0, 0, 0));
        btnConta.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnConta.setForeground(new java.awt.Color(255, 255, 255));
        btnConta.setText("Conta");
        btnConta.setBorder(null);
        btnConta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContaActionPerformed(evt);
            }
        });

        btnPlantas.setBackground(new java.awt.Color(0, 0, 0));
        btnPlantas.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnPlantas.setForeground(new java.awt.Color(255, 255, 255));
        btnPlantas.setText("Plantas");
        btnPlantas.setBorder(null);
        btnPlantas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantasActionPerformed(evt);
            }
        });

        btnJardim.setBackground(new java.awt.Color(0, 0, 0));
        btnJardim.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        btnJardim.setForeground(new java.awt.Color(255, 255, 255));
        btnJardim.setText("Meu Jardim");
        btnJardim.setBorder(null);
        btnJardim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnJardim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJardimActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnHome)
                .addGap(146, 146, 146)
                .addComponent(btnPlantas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(btnJardim)
                .addGap(128, 128, 128)
                .addComponent(btnConta)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome)
                    .addComponent(btnConta)
                    .addComponent(btnPlantas)
                    .addComponent(btnJardim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        MenuBar.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(MenuBar, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(30, 60, 42));

        painelJardim.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelJardimLayout = new javax.swing.GroupLayout(painelJardim);
        painelJardim.setLayout(painelJardimLayout);
        painelJardimLayout.setHorizontalGroup(
            painelJardimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        painelJardimLayout.setVerticalGroup(
            painelJardimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(407, 455));

        cbL1.setBackground(new java.awt.Color(255, 255, 255));
        cbL1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        cbL1.setForeground(new java.awt.Color(51, 51, 51));
        cbL1.setText("Lição 1: A escolha da planta ideal");
        cbL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbL1ActionPerformed(evt);
            }
        });

        cbL2.setBackground(new java.awt.Color(255, 255, 255));
        cbL2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        cbL2.setForeground(new java.awt.Color(51, 51, 51));
        cbL2.setText("Lição 2: Preparando o material");

        cbL3.setBackground(new java.awt.Color(255, 255, 255));
        cbL3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        cbL3.setForeground(new java.awt.Color(51, 51, 51));
        cbL3.setText("Lição 3: A base de tudo: drenagem");
        cbL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbL3ActionPerformed(evt);
            }
        });

        cbL4.setBackground(new java.awt.Color(255, 255, 255));
        cbL4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        cbL4.setForeground(new java.awt.Color(51, 51, 51));
        cbL4.setText("Lição 4: Preparando o berço da planta");

        cbL5.setBackground(new java.awt.Color(255, 255, 255));
        cbL5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        cbL5.setForeground(new java.awt.Color(51, 51, 51));
        cbL5.setText("Lição 5: O grande momento do plantio");

        cbL6.setBackground(new java.awt.Color(255, 255, 255));
        cbL6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        cbL6.setForeground(new java.awt.Color(51, 51, 51));
        cbL6.setText("Lição 6: O primeiro gole de vida");
        cbL6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbL6ActionPerformed(evt);
            }
        });

        bnnL6.setBackground(new java.awt.Color(100, 98, 254));
        bnnL6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        bnnL6.setForeground(new java.awt.Color(255, 255, 255));
        bnnL6.setText("Ver mais");
        bnnL6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnnL6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL6ActionPerformed(evt);
            }
        });

        bnnL5.setBackground(new java.awt.Color(100, 98, 254));
        bnnL5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        bnnL5.setForeground(new java.awt.Color(255, 255, 255));
        bnnL5.setText("Ver mais");
        bnnL5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnnL5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL5ActionPerformed(evt);
            }
        });

        bnnL4.setBackground(new java.awt.Color(100, 98, 254));
        bnnL4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        bnnL4.setForeground(new java.awt.Color(255, 255, 255));
        bnnL4.setText("Ver mais");
        bnnL4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnnL4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL4ActionPerformed(evt);
            }
        });

        bnnL3.setBackground(new java.awt.Color(100, 98, 254));
        bnnL3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        bnnL3.setForeground(new java.awt.Color(255, 255, 255));
        bnnL3.setText("Ver mais");
        bnnL3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnnL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL3ActionPerformed(evt);
            }
        });

        bnnL2.setBackground(new java.awt.Color(100, 98, 254));
        bnnL2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        bnnL2.setForeground(new java.awt.Color(255, 255, 255));
        bnnL2.setText("Ver mais");
        bnnL2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnnL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL2ActionPerformed(evt);
            }
        });

        bnnL1.setBackground(new java.awt.Color(100, 98, 254));
        bnnL1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        bnnL1.setForeground(new java.awt.Color(255, 255, 255));
        bnnL1.setText("Ver mais");
        bnnL1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnnL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnnL1ActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbL1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbL5)
                    .addComponent(cbL4)
                    .addComponent(cbL3)
                    .addComponent(cbL2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbL6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bnnL1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(bnnL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnnL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnnL4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnnL5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnnL6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(177, 177, 177))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnnL1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbL1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnnL2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbL2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbL3)
                    .addComponent(bnnL3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnnL4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbL4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnnL5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbL5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbL6)
                    .addComponent(bnnL6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Minha Jornada");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Meu Jardim");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelJardim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelJardim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarPlantas() {
    painelJardim.removeAll(); // Limpa o painel

    JardimDAO dao = new JardimDAO();
    ArrayList<PlantaJardim> lista = dao.buscarPlantasUsuario(Sessao.emailUsuarioLogado);

    for (PlantaJardim pj : lista) {

        JButton btn = new JButton(pj.getApelido() + " (" + pj.getNomePlanta() + ")");
        btn.setPreferredSize(new Dimension(180, 40));
        
        btn.setUI(new BasicButtonUI());
        
        btn.addActionListener(e -> {
            new PlantaEscolhidaView(pj).setVisible(true);
            this.dispose();
        });

        painelJardim.add(btn);
    }

    painelJardim.revalidate();
    painelJardim.repaint();
     
    
}


    private void escolherPlantaParaSubirNivel(int nivelDaLicao) {
        JardimDAO dao = new JardimDAO();
        ArrayList<PlantaJardim> lista = dao.buscarPlantasUsuario(Sessao.emailUsuarioLogado);

        // Se não tiver planta cadastrada
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Você ainda não adicionou nenhuma planta ao jardim!");
            return;
        }
        // Cria lista de nomes para exibir
        String[] nomes = new String[lista.size()];
        for (int i = 0; i < lista.size(); i++) {
            nomes[i] = lista.get(i).getApelido() + " (" + lista.get(i).getNomePlanta() + ")";
        }
        // Mostra escolha
        String selecionada = (String) JOptionPane.showInputDialog(
            this,
            "Selecione a planta que concluiu a lição:",
            "Concluir nível",
            JOptionPane.PLAIN_MESSAGE,
            null,
            nomes,
            nomes[0]
        );
        if (selecionada != null) {
            // Pega o item real
            PlantaJardim pjEscolhida = lista.get(java.util.Arrays.asList(nomes).indexOf(selecionada));
            // Sobe o nível no banco
            boolean ok = dao.atualizarNivelPlanta(
                Sessao.emailUsuarioLogado,
                pjEscolhida.getNomePlanta(),
                nivelDaLicao
            );
            if (ok) {
                JOptionPane.showMessageDialog(this, "Nível concluído com sucesso!");
                carregarPlantas(); // atualiza a tela
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar nível.");
            }
        }
    }

    
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
            NavegarView Conta = new NavegarView();
            Conta.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContaActionPerformed
            ContaView Conta = new ContaView();
            Conta.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnContaActionPerformed

    private void btnPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantasActionPerformed
            PlantasView planta = new PlantasView();
            planta.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnPlantasActionPerformed

    private void btnJardimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJardimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJardimActionPerformed

    private void cbL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbL1ActionPerformed

    private void cbL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbL3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbL3ActionPerformed

    private void bnnL6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL6ActionPerformed
        this.dispose();
        new LicaoView(
            "Lição 6: O Primeiro Gole de Vida",
            "A primeira rega é crucial após o plantio. Você deve regar abundantemente\n"
            + "até sair pelos furos, para eliminar bolsas de ar, assentar o substrato e hidratar\n"
            + "a planta após o estresse da mudança.", 6
        ).setVisible(true);
    }//GEN-LAST:event_bnnL6ActionPerformed

    private void bnnL5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL5ActionPerformed
        this.dispose();
        new LicaoView(
            "Lição 5: O Grande Momento do Plantio",
            "Aqui você aprende como posicionar a planta no novo vaso sem danificar as raízes.\n"
            + "Também aprende a completar as laterais com substrato e firmar a planta corretamente."
        ,5).setVisible(true);
    }//GEN-LAST:event_bnnL5ActionPerformed

    private void bnnL4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL4ActionPerformed
        this.dispose();
        new LicaoView(
            "Lição 4: Preparando o Berço da Planta",
            "Com a drenagem pronta, você prepara a 'cama' onde a planta viverá.\n"
            + "Esta lição ensina a criar a primeira camada de substrato, fofa e nutritiva,\n"
            + "na altura correta para acomodar o torrão sem deixar a planta funda ou alta demais."
        ,4).setVisible(true);
    }//GEN-LAST:event_bnnL4ActionPerformed

    private void bnnL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL3ActionPerformed
        this.dispose();
        new LicaoView(
            "Lição 3: A Base de Tudo: Drenagem",
            "A drenagem é essencial para evitar apodrecimento das raízes.\n"
            + "Aqui você aprende a criar a camada de drenagem perfeita usando argila expandida,\n"
            + "brita e manta geotêxtil, garantindo que a água nunca se acumule no vaso."
        ,3).setVisible(true);
    }//GEN-LAST:event_bnnL3ActionPerformed

    private void bnnL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL2ActionPerformed
        this.dispose();
        new LicaoView(
            "Lição 2: Preparando o Material",
            "Com sua nova planta escolhida, é hora de preparar o enxoval.\n"
            + "Aqui você aprende sobre tipos de vasos, tamanhos ideais e o substrato correto,\n"
            + "garantindo uma mistura nutritiva adequada para o desenvolvimento da planta."
       ,2 ).setVisible(true);
    }//GEN-LAST:event_bnnL2ActionPerformed

    private void bnnL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnnL1ActionPerformed
        this.dispose();
        new LicaoView(
            "Lição 1: A Escolha da Planta Ideal",
            "Nesta lição inicial, você aprende a base do sucesso: a compatibilidade.\n"
            + "Você vai explorar como analisar seu ambiente, identificando níveis de luz,\n"
            + "ventilação e espaço disponível. O objetivo é escolher uma planta que prospere\n"
            + "no seu lar, alinhando as necessidades dela com sua rotina."
        ,1).setVisible(true);
        
    }//GEN-LAST:event_bnnL1ActionPerformed

    private void cbL6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbL6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbL6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeuJardimView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeuJardimView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeuJardimView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeuJardimView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeuJardimView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuBar;
    private javax.swing.JButton bnnL1;
    private javax.swing.JButton bnnL2;
    private javax.swing.JButton bnnL3;
    private javax.swing.JButton bnnL4;
    private javax.swing.JButton bnnL5;
    private javax.swing.JButton bnnL6;
    private javax.swing.JButton btnConta;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJardim;
    private javax.swing.JButton btnPlantas;
    private javax.swing.JCheckBox cbL1;
    private javax.swing.JCheckBox cbL2;
    private javax.swing.JCheckBox cbL3;
    private javax.swing.JCheckBox cbL4;
    private javax.swing.JCheckBox cbL5;
    private javax.swing.JCheckBox cbL6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel painelJardim;
    // End of variables declaration//GEN-END:variables
}
