package br.login.view;

import br.login.model.PlantaJardim;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;

public class PlantaEscolhidaView extends javax.swing.JFrame {

    private PlantaJardim planta;

    // Construtor vazio bloqueado para evitar abrir sem planta
    private PlantaEscolhidaView() {
        throw new UnsupportedOperationException("Use PlantaEscolhidaView(planta)");
    }

    // Construtor correto recebendo a planta
    public PlantaEscolhidaView(PlantaJardim planta) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.planta = planta;

        // Remove UI padrão dos botões
        JButton[] btns = {btnHome, btnPlantas, btnJardim, btnConta, btnVoltar};
        for (JButton btn : btns) {
            btn.setUI(new BasicButtonUI());
        }

        // Preenche os textos
        lblNomeReal.setText(planta.getNomePlanta()+":");
        lblApelido.setText(planta.getApelido());

        // Marca níveis
        marcarNiveis(planta.getNivel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuBar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnConta = new javax.swing.JButton();
        btnPlantas = new javax.swing.JButton();
        btnJardim = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        lblNomeReal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblApelido = new javax.swing.JLabel();
        cbL1 = new javax.swing.JCheckBox();
        cbL2 = new javax.swing.JCheckBox();
        cbL3 = new javax.swing.JCheckBox();
        cbL4 = new javax.swing.JCheckBox();
        cbL5 = new javax.swing.JCheckBox();
        cbL6 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        MenuBar.setBackground(new java.awt.Color(0, 0, 0));
        MenuBar.setPreferredSize(new java.awt.Dimension(0, 60));
        MenuBar.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        MenuBar.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        MenuBar.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome.setText(" Home");
        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnConta.setBackground(new java.awt.Color(0, 0, 0));
        btnConta.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnConta.setForeground(new java.awt.Color(255, 255, 255));
        btnConta.setText("Conta");
        btnConta.setBorder(null);
        btnConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContaActionPerformed(evt);
            }
        });

        btnPlantas.setBackground(new java.awt.Color(0, 0, 0));
        btnPlantas.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnPlantas.setForeground(new java.awt.Color(255, 255, 255));
        btnPlantas.setText("Plantas");
        btnPlantas.setBorder(null);
        btnPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantasActionPerformed(evt);
            }
        });

        btnJardim.setBackground(new java.awt.Color(0, 0, 0));
        btnJardim.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        btnJardim.setForeground(new java.awt.Color(255, 255, 255));
        btnJardim.setText("Meu Jardim");
        btnJardim.setBorder(null);
        btnJardim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJardimActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnHome)
                .addGap(146, 146, 146)
                .addComponent(btnPlantas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(btnJardim)
                .addGap(128, 128, 128)
                .addComponent(btnConta)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome)
                    .addComponent(btnConta)
                    .addComponent(btnPlantas)
                    .addComponent(btnJardim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        MenuBar.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(MenuBar, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(30, 60, 42));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(51, 51, 51));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblNomeReal.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        lblNomeReal.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        lblApelido.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        lblApelido.setForeground(new java.awt.Color(51, 51, 51));

        cbL1.setBackground(new java.awt.Color(255, 255, 255));
        cbL1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        cbL1.setForeground(new java.awt.Color(51, 51, 51));
        cbL1.setText("Lição 1");
        cbL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbL1ActionPerformed(evt);
            }
        });

        cbL2.setBackground(new java.awt.Color(255, 255, 255));
        cbL2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        cbL2.setForeground(new java.awt.Color(51, 51, 51));
        cbL2.setText("Lição 2");
        cbL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbL2ActionPerformed(evt);
            }
        });

        cbL3.setBackground(new java.awt.Color(255, 255, 255));
        cbL3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        cbL3.setForeground(new java.awt.Color(51, 51, 51));
        cbL3.setText("Lição 3");
        cbL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbL3ActionPerformed(evt);
            }
        });

        cbL4.setBackground(new java.awt.Color(255, 255, 255));
        cbL4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        cbL4.setForeground(new java.awt.Color(51, 51, 51));
        cbL4.setText("Lição 4");

        cbL5.setBackground(new java.awt.Color(255, 255, 255));
        cbL5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        cbL5.setForeground(new java.awt.Color(51, 51, 51));
        cbL5.setText("Lição 5");

        cbL6.setBackground(new java.awt.Color(255, 255, 255));
        cbL6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        cbL6.setForeground(new java.awt.Color(51, 51, 51));
        cbL6.setText("Lição 6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNomeReal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnVoltar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbL1)
                            .addComponent(cbL2)
                            .addComponent(cbL3)
                            .addComponent(cbL4)
                            .addComponent(cbL5)
                            .addComponent(cbL6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnVoltar)
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeReal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(cbL1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbL2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbL3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbL4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbL5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbL6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void marcarNiveis(int nivel) {
        cbL1.setSelected(nivel >= 1);
        cbL2.setSelected(nivel >= 2);
        cbL3.setSelected(nivel >= 3);
        cbL4.setSelected(nivel >= 4);
        cbL5.setSelected(nivel >= 5);
        cbL6.setSelected(nivel >= 6);

        cbL1.setEnabled(false);
        cbL2.setEnabled(false);
        cbL3.setEnabled(false);
        cbL4.setEnabled(false);
        cbL5.setEnabled(false);
        cbL6.setEnabled(false);
    }
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
            NavegarView Conta = new NavegarView();
            Conta.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContaActionPerformed
        // TODO add your handling code here:
            ContaView Conta = new ContaView();
            Conta.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnContaActionPerformed

    private void btnPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantasActionPerformed
        // TODO add your handling code here:
            PlantasView planta = new PlantasView();
            planta.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnPlantasActionPerformed

    private void btnJardimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJardimActionPerformed
        // TODO add your handling code here:
            MeuJardimView jardim = new MeuJardimView();
            jardim.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnJardimActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
            MeuJardimView jardim = new MeuJardimView();
            jardim.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbL1ActionPerformed

    private void cbL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbL2ActionPerformed

    private void cbL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbL3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbL3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantaEscolhidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantaEscolhidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantaEscolhidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantaEscolhidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlantaEscolhidaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuBar;
    private javax.swing.JButton btnConta;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJardim;
    private javax.swing.JButton btnPlantas;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox cbL1;
    private javax.swing.JCheckBox cbL2;
    private javax.swing.JCheckBox cbL3;
    private javax.swing.JCheckBox cbL4;
    private javax.swing.JCheckBox cbL5;
    private javax.swing.JCheckBox cbL6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblApelido;
    private javax.swing.JLabel lblNomeReal;
    // End of variables declaration//GEN-END:variables
}
