/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.login.view;

import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author mayar
 */
public class PlantasView extends javax.swing.JFrame {

    /**
     * Creates new form PlantasView
     */
    public PlantasView() {
        initComponents();
        this.setLocationRelativeTo(null);
        JButton[] btns={btnHome,btnPlantas,btnJardim,btnConta,btnPesquisar};
        for(JButton btn:btns){
            btn.setUI(new BasicButtonUI());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoPlanta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        MenuBar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnConta = new javax.swing.JButton();
        btnPlantas = new javax.swing.JButton();
        btnJardim = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdbAlimenticia = new javax.swing.JRadioButton();
        rdbOrnamental = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cbSolo = new javax.swing.JComboBox<>();
        txtNomePlanta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        MenuBar.setBackground(new java.awt.Color(0, 0, 0));
        MenuBar.setPreferredSize(new java.awt.Dimension(0, 60));
        MenuBar.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        MenuBar.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        MenuBar.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome.setText(" Home");
        btnHome.setBorder(null);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnConta.setBackground(new java.awt.Color(0, 0, 0));
        btnConta.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnConta.setForeground(new java.awt.Color(255, 255, 255));
        btnConta.setText("Conta");
        btnConta.setBorder(null);
        btnConta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContaActionPerformed(evt);
            }
        });

        btnPlantas.setBackground(new java.awt.Color(0, 0, 0));
        btnPlantas.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        btnPlantas.setForeground(new java.awt.Color(255, 255, 255));
        btnPlantas.setText("Plantas");
        btnPlantas.setBorder(null);
        btnPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantasActionPerformed(evt);
            }
        });

        btnJardim.setBackground(new java.awt.Color(0, 0, 0));
        btnJardim.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnJardim.setForeground(new java.awt.Color(255, 255, 255));
        btnJardim.setText("Meu Jardim");
        btnJardim.setBorder(null);
        btnJardim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnJardim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJardimActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnHome)
                .addGap(146, 146, 146)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnPlantas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(btnJardim)
                        .addGap(128, 128, 128)
                        .addComponent(btnConta)
                        .addGap(81, 81, 81))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome)
                    .addComponent(btnConta)
                    .addComponent(btnPlantas)
                    .addComponent(btnJardim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        MenuBar.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(MenuBar, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(30, 60, 42));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Pesquise");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tipo de planta");

        rdbAlimenticia.setBackground(new java.awt.Color(255, 255, 255));
        grupoTipoPlanta.add(rdbAlimenticia);
        rdbAlimenticia.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        rdbAlimenticia.setForeground(new java.awt.Color(51, 51, 51));
        rdbAlimenticia.setText("Alimentícias");
        rdbAlimenticia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdbAlimenticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAlimenticiaActionPerformed(evt);
            }
        });

        rdbOrnamental.setBackground(new java.awt.Color(255, 255, 255));
        grupoTipoPlanta.add(rdbOrnamental);
        rdbOrnamental.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        rdbOrnamental.setForeground(new java.awt.Color(51, 51, 51));
        rdbOrnamental.setText("Ornamental");
        rdbOrnamental.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Solo");

        cbSolo.setBackground(new java.awt.Color(255, 255, 255));
        cbSolo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        cbSolo.setForeground(new java.awt.Color(51, 51, 51));
        cbSolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arenoso", "Argiloso", "Siltoso", "Humífero" }));
        cbSolo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSoloActionPerformed(evt);
            }
        });

        txtNomePlanta.setBackground(new java.awt.Color(255, 255, 255));
        txtNomePlanta.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        txtNomePlanta.setForeground(new java.awt.Color(51, 51, 51));
        txtNomePlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePlantaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nome");

        btnPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        btnPesquisar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Buscar");
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(255, 255, 255));
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info(1).png"))); // NOI18N
        btnInfo.setBorder(null);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdbAlimenticia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbOrnamental))
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInfo)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtNomePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbAlimenticia)
                    .addComponent(rdbOrnamental)
                    .addComponent(cbSolo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plantinhas 2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(45, 45, 45))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
            NavegarView Conta = new NavegarView();
            Conta.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContaActionPerformed
            ContaView Conta = new ContaView();
            Conta.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnContaActionPerformed

    private void btnPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlantasActionPerformed

    private void btnJardimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJardimActionPerformed
            MeuJardimView jardim = new MeuJardimView();
            jardim.setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnJardimActionPerformed

    private void cbSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSoloActionPerformed

    private void txtNomePlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePlantaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        //pega o tipo
        String tipoPlanta = "";
        if (rdbOrnamental.isSelected()) {
            tipoPlanta = "Ornamental";
        } else if (rdbAlimenticia.isSelected()) {
            tipoPlanta = "Alimentícia";
        }

        //pega o solo
        String tipoSolo = cbSolo.getSelectedItem().toString();

        //pega o nome (texto)
        String nomePlanta = txtNomePlanta.getText();

        //se tiver vazio o tipo
        if (tipoPlanta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione o tipo de planta!");
            return;
        }

        //faz a consulta
        br.login.dao.PlantaDAO dao = new br.login.dao.PlantaDAO();
        java.util.ArrayList<br.login.model.Planta> lista = dao.pesquisarPlantas(tipoPlanta, tipoSolo, nomePlanta);

        //se nao encontrar
        if (lista.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhuma planta encontrada!");
            return;
        }

        //deixa selecionar a planta que encontrou
        String[] nomesPlantas = lista.stream()
        .map(p -> p.getNome())
        .toArray(String[]::new);

        String plantaSelecionada = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Selecione a planta desejada:",
            "Resultados da Pesquisa",
            javax.swing.JOptionPane.PLAIN_MESSAGE,
            null,
            nomesPlantas,
            nomesPlantas[0]
        );

        if (plantaSelecionada == null) return; // cancelou

        //encontra o objeto da planta escolhida
        br.login.model.Planta p = lista.stream()
        .filter(item -> item.getNome().equals(plantaSelecionada))
        .findFirst()
        .orElse(null);

        if (p == null) return;

        //mensagem
        String mensagemBonita =
        "*Planta Encontrada!*\n\n" +
        "Nome: " + p.getNome() + "\n" +
        "Tipo: " + p.getTipo() + "\n" +
        "Solo Ideal: " + p.getSolo() + "\n\n" +
        "Descrição:\n" + p.getDescricao() + "\n\n" +
        "Deseja adicionar esta planta ao seu jardim?";

        int opcao = javax.swing.JOptionPane.showOptionDialog(
            this,
            mensagemBonita,
            "Detalhes da Planta",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.INFORMATION_MESSAGE,
            null,
            new Object[]{"Adicionar", "Fechar"},
            "Adicionar"
        );

        //adicionar
        if (opcao == 0) {

            String nomePersonalizado = javax.swing.JOptionPane.showInputDialog(
                this,
                "Dê um nome à sua planta:"
            );

            if (nomePersonalizado != null && !nomePersonalizado.isEmpty()) {
                br.login.dao.JardimDAO jardimDao = new br.login.dao.JardimDAO();
                boolean sucesso = jardimDao.adicionarPlanta(
                    br.login.dao.Sessao.emailUsuarioLogado,
                    p.getNome(),
                    nomePersonalizado
                );

                if (sucesso) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Planta adicionada ao seu jardim!");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Erro ao adicionar planta.");
                }
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void rdbAlimenticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAlimenticiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbAlimenticiaActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, ""
                + "1. Solo Arenoso : É o solo típico de praia ou dunas. Ele é muito permeável, ou seja, a água passa por ele rapidamente e ele seca depressa.\n" +
                  "  ➥ Características - Cores claras, geralmente amarelo ou branco.\n\n"+
                  "2. Solo Argiloso : \"Barro\" vermelho ou amarelado. É um solo denso que retém muita água e nutrientes, mas fica muito duro quando seca.\n" +
                  "  ➥ Características - Cores vivas (vermelho, laranja ou cinza).Se assemelha a uma massinha de modelar, massa única e sem espaços.\n\n"+
                  "3. Solo Siltoso : É o meio-termo entre a areia e a argila. É muito comum em leitos de rios e sofre muita erosão (vira poeira fácil).\n" +
                  "  ➥ Características - Quando seco é macio e sedoso. Quando molhado, ele é liso e escorregadio, mas não é pegajoso como a argila. Ele suja a mão, mas sai fácil com água.\n\n"+
                  "4. Solo Humífero : É a \"terra de jardim\", rica em matéria orgânica (restos de plantas e animais em decomposição). É o melhor para o plantio.\n" +
                  "  ➥ Características - Cor muito escura (preto ou marrom café). É fofo, macio e húmido.");
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlantasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuBar;
    private javax.swing.JButton btnConta;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnJardim;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPlantas;
    private javax.swing.JComboBox<String> cbSolo;
    private javax.swing.ButtonGroup grupoTipoPlanta;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdbAlimenticia;
    private javax.swing.JRadioButton rdbOrnamental;
    private javax.swing.JTextField txtNomePlanta;
    // End of variables declaration//GEN-END:variables
}
